Optimize robots
Signed-off-by: tao.yang <tao.yang@daocloud.io>

diff --git a/.github/workflows/auto-cherrypick.yaml b/.github/workflows/auto-cherrypick.yaml
--- a/.github/workflows/auto-cherrypick.yaml
+++ b/.github/workflows/auto-cherrypick.yaml
@@ -26,14 +26,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      # ${{ secrets.GITHUB_TOKEN }} is forbidden to create or approve pull requests
+      - uses: crazy-max/ghaction-import-gpg@v6
+        with:
+          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.GPG_PASSPHRASE }}
+          git_user_signingkey: true
+          git_commit_gpgsign: true
+
       - name: cherry pick
         env:
-          GITHUB_TOKEN: ${{ secrets.WELAN_PAT}}
+          GITHUB_TOKEN: ${{ secrets.WELAN_PAT }}
           JSON: ${{ toJSON(github) }}
         run: |
           set -x
@@ -41,11 +47,11 @@ jobs:
           if ${{ github.event_name == 'workflow_dispatch' }}; then
                 PR_NUMBER=${{ github.event.inputs.prNumber }}
           else
-                    grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" || true
+                grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" || true
                 echo "try to get PR from commit"
                 COMMIT=` echo "${JSON}" | jq '.event.commits[0].id' | tr -d '"' ` || true
                 if [ -n "${COMMIT}" ]; then
-                    PR_NUMBER=`curl -s -H "Accept: application/vnd.github.groot-preview+json"  https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT}/pulls | jq -r '.[].number' `
+                    PR_NUMBER=`curl  --retry 10  -s -H "Accept: application/vnd.github.groot-preview+json"  https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT}/pulls | jq -r '.[].number' `
                 else
                     echo "error, failed to get any commit ID"
                 fi
@@ -63,7 +69,7 @@ jobs:
                 #    [ -n "${PR_AUTHOR}" ] || { echo "no PR_AUTHOR, ignore" ; }
           #
           fi
-          RP_API_BODY=` curl https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} -s -H "Accept: application/vnd.github.groot-preview+json" `
+          RP_API_BODY=` curl  --retry 10  https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} -s -H "Accept: application/vnd.github.groot-preview+json" `
           PR_COMMITS=` echo "${RP_API_BODY}" |  jq ' .merge_commit_sha ' | tr -d '"' `
           PR_AUTHOR=` echo "${RP_API_BODY}" |  jq ' .user.login ' | tr -d '"' `
           PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
@@ -90,25 +96,31 @@ jobs:
           #
           echo "=============================== get dest branch from labels ======== "
           WANT_MERGE_BRANCH_LIST=""
+          INITIAL_LABEL=""
           if ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destBranch != '' }}; then
                 WANT_MERGE_BRANCH_LIST=${{ github.event.inputs.destBranch }}
           else
                 for LABEL in ${PR_LABEL} ; do
                     echo "checking label $LABEL "
                     PREFIX="${{ env.PR_LABEL_PREFIX_CHERRYPICK }}"
-                    grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null || continue
+                    if ! grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null; then
+                        INITIAL_LABEL+="${LABEL},"
+                        continue
+                    fi
                     BRANCH_NAME=` sed 's?'"${PREFIX}"'??' <<< "$LABEL" `
                     WANT_MERGE_BRANCH_LIST+=" $BRANCH_NAME "
                 done
           fi
           [ -z "$WANT_MERGE_BRANCH_LIST" ] && echo "no branch to cherry pick" && exit 0
           echo "cherry pick to $WANT_MERGE_BRANCH_LIST "
+          INITIAL_LABEL="${INITIAL_LABEL%,}"
+          echo "INITIAL_LABEL: ${INITIAL_LABEL}"
           #
           #
           echo "============ begin to cherry pick ============ "
           FINAL_FAILURE=false
           git branch
-          git config  user.email "robot@example.com"
+          git config  user.email "tao.yang@daocloud.io"
           git config  user.name "robot"
           gh label create ${{ env.CHERRYPICK_LABEL }} || true
           for BRANCH in $WANT_MERGE_BRANCH_LIST ; do
@@ -151,7 +163,7 @@ jobs:
                     if ! ERROR_MESSAGE=`git cherry-pick -m 1 $COMMIT 2>&1` ; then
                           echo ">>>>>>>>>>>> fail when cherry pick $COMMIT to branch $BRANCH "
                           echo "$ERROR_MESSAGE"
-                          echo "---- failure detail"
+                          echo "---- failuire detail"
                           git status
                           git diff
                           echo "<<<<<<<<<<<<<"
@@ -175,9 +187,9 @@ jobs:
               if [ "$FAIL" == "true" ] ; then
                   echo "failed to cherry pick to branch $BRANCH "
                   FINAL_FAILURE=true
-                  echo -e "commits $PR_COMMITS conflict when merging to branch $BRANCH, please manually cherry pick it by yourself. \n PR <${PR_URL}> ,  action <${ACTION_URL}>  \n\n  \`\`\`\n${ERROR_MESSAGE}\n\`\`\` " | \
+                  echo -e "commits $PR_COMMITS of ${PR_AUTHOR} conflict when merging to branch $BRANCH, please manually cherry pick it by yourself. \n PR <${PR_URL}> ,  action <${ACTION_URL}>  \n\n  \`\`\`\n${ERROR_MESSAGE}\n\`\`\` " | \
                        gh issue create  \
-                        --title "failed to auto cherry pick PR ${PR_NUMBER} to branch ${BRANCH}" \
+                        --title "failed to cherry pick PR ${PR_NUMBER} from ${PR_AUTHOR}, to branch ${BRANCH}" \
                         --label "${{ env.CHERRYPICK_LABEL }}" \
                         --assignee "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}" \
                         --body-file -
@@ -185,11 +197,12 @@ jobs:
               if [ "$UPDATE" == "true" ] ; then
                   echo "succeeded to cherry pick to branch $BRANCH "
                   # create a pr
+                  git commit -s -S --amend --no-edit
                   git push origin ${PR_BRANCH}:${PR_BRANCH} -f
                   gh pr create --title "${PR_TITLE}" \
                       --assignee "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}" \
-                      --label ${{ env.CHERRYPICK_LABEL }} \
-                      --body "robot cherry pick pr <${PR_URL}> to branch ${BRANCH},  action <${ACTION_URL}>  , commits $PR_COMMITS " \
+                      --label "${{ env.CHERRYPICK_LABEL }},${INITIAL_LABEL}" \
+                      --body "robot cherry pick PR <${PR_URL}> from ${PR_AUTHOR},to branch ${BRANCH},  action <${ACTION_URL}>  , commits $PR_COMMITS " \
                       --base ${BRANCH}
               else
                   echo "no changes happened for commits $PR_COMMITS, ignore create pr"
@@ -198,7 +211,7 @@ jobs:
           echo "=========== check result ============"
           if [ "$FINAL_FAILURE" == "true" ] ; then
               # if failed to create issue or pr, fails
-              echo "error, failure happened"
+              echo "error, failuire happened"
           else
               echo "all done"
           fi
